# Generated by Django 3.2 on 2021-04-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OGE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ex1',
            new_name='Model_Word',
        ),
    ]
